### ISSUE TITLE
"INSERT ... SELECT Syntax" return ConnectionException

### ISSUE THREAD

**Issue by 0x39** [amphp/mysql#89] opened 2019-10-15 13:29 UTC
`
INSERT INTO tbl_temp2 (fld_id)
  SELECT tbl_temp1.fld_order_id
  FROM tbl_temp1 WHERE tbl_temp1.fld_order_id > 100;
`

**Produce Exception:** 
`
[Amp\Sql\ConnectionException]                                                                              
  Connection went away... unable to fulfil this deferred ... It's unknown whether the query was executed...
`

**Comment by trowski** [comment] 2019-10-15 14:51
I'm not able to reproduce this. Can you please tell me what MySQL (or MariaDB) version and what version of PHP you're using?

**Comment by 0x39** [comment] 2019-10-15 15:27
PHP 7.2.19
10.2.26-MariaDB

`Amp\Loop::run(function () use ($output, $channelDates) {

            $db = Mysql\pool($this->connectionConfig);

            $q = "INSERT INTO aggregated_ads_by_day (date, channel_id, advertiser_tag_id, broadcast_count, broadcast_duration, views, usage_status, created_at, updated_at)
                    SELECT 
                        FROM_UNIXTIME(starts_ts/1000, '%Y-%m-%d') as date,
                        channel_id,
                        advertiser_tag_id,
                        COUNT(id) as broadcast_count,
                        SEC_TO_TIME(SUM((ends_ts - starts_ts)/1000)) as broadcast_duration,
                        SUM(views) as views,
                        'new',
                        NOW(),
                        NOW()
                        
                        FROM video_cuts
                        WHERE deleted_at IS NULL
                        AND channel_id = '1'
                        AND FROM_UNIXTIME(starts_ts/1000, '%Y-%m-%d') = '2017-11-07'
                        
                        GROUP BY FROM_UNIXTIME(starts_ts/1000, '%Y-%m-%d'), advertiser_tag_id";

            yield $db->query($q);
});
`

**Comment by trowski** [comment] 2019-10-15 16:32
Can you tell me if it works with `dev-master`?

**Comment by 0x39** [comment] 2019-10-16 10:00
Its definitely problem with this type of query, when i remove INSERT before SELECT, no exceptions produced.

**Comment by trowski** [comment] 2019-11-16 16:03
I added a test that does an `INSERT ... SELECT` query, which passes with all tested versions of MySQL/MariaDB. Do you have some minimal example that fails? Everything I tried appeared to work.

**Comment by bwoebi** [comment] 2019-11-20 10:18
Another possibility would be to set `const MYSQL_DEBUG = true;` and share its output - so that we can actually inspect what is being sent and how the server replies.

**Comment by magussiro** [comment] 2021-03-25 07:38
you can test your query in other client to check the query is valid, maybe is mysql execution time over

check timeout var like the:show variables like '%timeout%';

**Comment by trowski** [comment] 2022-02-27 17:11
Closing as we have not received feedback in some time. I was not able to replicate this issue. Feel free to reopen this issue or create a new one if you need more assistance.

**Closed by trowski** 2022-02-27 17:11 UTC
