### ISSUE TITLE
Undefined index in unmapConnection

### ISSUE THREAD

**Issue by kelunik** [amphp/mysql#7] opened 2015-01-23 11:29 UTC
[`Notice: Undefined index: 000000002f21b38f000000002e01fac2 in mysql/lib/Pool.php on line 242`](https://github.com/amphp/mysql/blob/master/lib/Pool.php#L242)

There should be a check if that key exists.

**Comment by bwoebi** [comment] 2015-01-23 12:13
How can I reproduce this bug? There shouldn't be a check, it's a bug somewhere else if the index isn't defined there.

**Comment by kelunik** [comment] 2015-01-23 13:22
I don't really know, could be due to notebook energy saving state?

**Comment by bwoebi** [comment] 2015-01-23 13:27
That could be the reason why a connection breaks, but not why this emits a notice...

**Comment by kelunik** [comment] 2015-01-23 17:38
When does this method get called?

**Comment by bwoebi** [comment] 2015-01-23 17:48
When a connection fails. (in config->restore callback and in the when() when it fails upon initialization).

**Comment by douggr** [comment] 2015-02-20 15:56
I got it (I think).

From http://php.net/stream_socket_client
> UDP sockets will sometimes appear to have opened without an error, even if
> the remote host is unreachable. The error will only become apparent when you
> read or write data to/from the socket. The reason for this is because UDP is
> a "connectionless" protocol, which means that the operating system does not
> try to establish a link for the socket until it actually needs to send or
> receive data. 

So connecting to any reachable IP address might open the connection failing silently.

**Comment by douggr** [comment] 2015-02-20 16:01
Question, this should apply to amphp/mysql or [rdlowrey/nbsock](/rdlowrey/nbsock/blob/master/lib/Connector.php#L136)?

cc /@rdlowrey

**Comment by douggr** [comment] 2015-02-20 19:09
Also related to #5 perhaps?

**Comment by kelunik** [comment] 2015-02-20 19:59
@douggr It's all TCP, I think only DNS uses UDP.

**Comment by douggr** [comment] 2015-02-20 21:18
Good call.

Despite a valid stream is created, empty even, the connection may or may not
be valid; you don't know until you read from it.

Since `onRead()` is called only within `onInit()` maybe this
douggr/mysql@2cf671a fix the whole thing?

**Comment by bwoebi** [comment] 2015-02-20 21:28
@douggr onRead() is the general callback for the read watcher, just the first read is in onInit(), which then invokes onRead(). … So, no.

**Comment by kelunik** [comment] 2015-02-20 21:28
It's called every time the socket is readable, see https://github.com/douggr/mysql/blob/master/lib/Connection.php#L168

**Comment by bwoebi** [comment] 2015-05-11 20:36
This bug was fixed in f50e75

**Closed by bwoebi** 2015-05-11 20:36 UTC
Labels: bug
